config/routes.rb
Rails.application.routes.draw do

  delete "empty_cart" => "shopping_cart_items#empty_cart", as: :empty_cart

  get "search" => "items#search"
  get "contact" => "items#contact"
  get "newslettersignup" => "shared#newslettersignup"
  get "legal" => "items#legal"

  resources :shopping_cart_items
  resources :items
  devise_for :users

  root 'items#index'


end

app/models/item.rb
class Item < ActiveRecord::Base

  def self.search(search)
    where("name ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
  private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :item_present
  validate :item_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_order

    def current_order
      if !session[:order_id].nil?
        Order.find(session[:order_id])
      else
        Order.new
      end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @shopping_cart_items = session[:shopping_cart]

    if params[:search]
          @items = Item.search(params[:search])
          render :search
        else
          @items = Item.all.order('created_at DESC')
        end
end
  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :quantity, :image)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
     @order = current_order
     @order_item = @order.order_items.new(order_item_params)
     @order.save
     session[:order_id] = @order.id
   end

   def update
     @order = current_order
     @order_item = @order.order_items.find(params[:id])
     @order_item.update_attributes(order_item_params)
     @order_items = @order.order_items
   end

   def destroy
     @order = current_order
     @order_item = @order.order_items.find(params[:id])
     @order_item.destroy
     @order_items = @order.order_items
   end
 private
   def order_item_params
     params.require(:order_item).permit(:quantity, :item_id)
   end
 end

app/controllers/shopping_cart_items_controller.rb
class ShoppingCartItemsController < ApplicationController


  def create
    session[:shopping_cart] ||= {}
    product_id = shopping_cart_item_params[:item_id]
    quantity = shopping_cart_item_params[:quantity].to_i
    session[:shopping_cart][product_id] ||= 0
    session[:shopping_cart][product_id] += quantity
    redirect_to items_path
  end

  def destroy
    session[:shopping_cart] ||= {}
    session[:shopping_cart].except!(params[:id])

    if session[:shopping_cart] == {}
      session[:shopping_cart] = nil
    end

    redirect_to items_path
  end

  def empty_cart
    session[:shopping_cart] ||= {}
    session[:shopping_cart] = nil

    redirect_to items_path
  end

  protected

  def shopping_cart_item_params
    params.permit(:item_id, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/shopping_cart_items_helper.rb
module ShoppingCartItemsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= item.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :item_id, value: item.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.item.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', item: order_item.item, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<li>
  <%= link_to image_tag(item.image, class: "index-img"), item_path(item.id) %>
  <div class="test">
    <div class="tag">Name:  <%= item.name %></div>
    <div class="tag">Price:  $<%= item.price %></div>
    <div class="tag">Quantity:  <%= item.quantity %></div>
    <div class="atc_button"><p class="atc"><%= link_to 'Add to cart', shopping_cart_items_path(item_id: item.id, quantity: 1), method: :post  %></p></div>
  </div>
</li>

app/views/items/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= item.name %></small></h4>
      <h4><%= item.image %></small></h4>


    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency item.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :item_id, value: item.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/items/contact.html.erb
<div class="container">
<div class="row">
  <div class="col-md-12">
  <form role="form" action="" method="post" >
    <div class="col-lg-6">
      <div class="well well-sm"><strong><i class="glyphicon glyphicon-ok form-control-feedback"></i> Required Field</strong></div>
      <div class="form-group">
        <label for="InputName">Your Name</label>
        <div class="input-group">
          <input type="text" class="form-control" name="InputName" id="InputName" placeholder="Enter Name" required>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span></div>
      </div>
      <div class="form-group">
        <label for="InputEmail">Your Email</label>
        <div class="input-group">
          <input type="email" class="form-control" id="InputEmail" name="InputEmail" placeholder="Enter Email" required  >
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span></div>
      </div>
      <div class="form-group">
        <label for="InputMessage">Message</label>
        <div class="input-group"
>
          <textarea name="InputMessage" id="InputMessage" class="form-control" rows="5" required></textarea>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span></div>
      </div>
      <div class="form-group">
        <label for="InputReal">What is 4+3? (Simple Spam Checker)</label>
        <div class="input-group">
          <input type="text" class="form-control" name="InputReal" id="InputReal" required>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span></div>
      </div>
      <input type="submit" name="submit" id="submit" value="Submit" class="btn btn-info pull-right">
    </div>
  </form>

</div>

</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class='bglogo'>
  <div class = "headerindex">
    <center><img id='logo' src="http://res.cloudinary.com/codaisseur/image/upload/v1461332270/HORRIFY_f7wdkk.png"><br>
      <img id='namelogo' src="http://res.cloudinary.com/codaisseur/image/upload/v1461332270/name_jyqlgg.png">
    </center>
  </div>
</div>

<p id="notice"><%= notice %></p>
<div class="container-fluid index">

<div class="welcome">
YOU NEED AN HOURGLASS. <i>TODAY</i>
</div>

  <ul class="bxslider">
  <%= render @items %>

  
  </ul>
  <!-- <%= link_to 'New Item', new_item_path %> -->
</div>
<div class='spacing'></div>
<%= render 'shared/cart' %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<div class="container">
  <h1>Search Results</h1>

  <p>all of your results </p>


  <% if @items.count > 0 %>
    <ul class="bxslider">
      <%= render @items %>
    </ul>
  <% else %>
    <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
  <% end %>
</div>

app/views/items/show.html.erb
<center>
   <%= image_tag(@item.image, class:"imgitem")%>

<br>
  <div class='title_item'><%= @item.name %></div>
<br>
<br>
<div class='showblock'>
  <div id='descript'><%= @item.description %></div>
<br>
<strong>PRICE:</strong>
  <i><%= @item.price %></i>
  <br /> <br />

  <div id="previous-item">
    <% if @item.id != Item.first[:id] %>
      <%= link_to "Prev", item_path(@item.id - 1) %>
    <% end %>
  </div>

  <div id="next-item">
    <% if @item.id != Item.last[:id] %>
      <%= link_to "Next", item_path(@item.id + 1) %>
    <% end %>
  </div>

  <div class="atc_button"><p class="atc"><%= link_to 'Add to cart', shopping_cart_items_path(item_id: @item.id, quantity: 1), method: :post  %></p></div>
</div>
</div>
</center>
<div class="cart-pos-show">
<%= render 'shared/cart' %>

</div>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HourGlass</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navigation' %>
<%= yield %>


</body>
<footer>

  <%= render 'shared/footer' %>

</footer>
</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/shared/_cart.html.erb
<div class="trigger">
  <img src="http://666marine.com/Shopping_Cart_Logo_op_800x571.png" />
</div>
<div class="cart-content">
<!--  <%= session[:shopping_cart] %> -->
  <p class="cart-title"> Shopping cart Overview</p>
  <% if session[:shopping_cart] != nil %>
    <% session[:shopping_cart].each do |item_id, quantity| %>
    <div class="cart-item-container">
      <p class="cart-item">
        <% item = Item.find(item_id.to_i) %>
        <%= image_tag(item.image, class: "cart-img") %>
      </p>
      <p class="cart-item-desc">
        <%= item.name %> |
        <%= quantity %><br />
        $<%= item.price %>
        <br />
          <p class="remove-button">
            <%= link_to 'X', shopping_cart_item_path(item.id), method: :delete, class: "remove" %>
          </p>
      <br />
      </p>
    </div>
    <% end %>
    <br />
    <% if session[:shopping_cart].length > 1 %>
     <%= link_to 'Empty cart', empty_cart_path(1), method: :delete, class: "empty" %>
   <% end %>
  <% end %>

</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<center>
<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Hourify </h3>
                    <ul>
                        <li><%= link_to "Our Store", "footer_path" %></li>
                        <li><%= link_to "Privacy Policy", "footer_path" %></li>
                        <li><%= link_to "Legal", "legal_path" %></li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Customers </h3>
                    <ul>
                      <li><%= link_to "Help", "footer_path" %></li>
                      <li><%= link_to "FAQ", "footer_path" %></li>
                      <li><%= link_to "Chat", "footer_path" %></li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Orders </h3>
                    <ul>
                      <li><%= link_to "Cart", "footer_path" %></li>
                      <li><%= link_to "Shipping", "footer_path" %></li>
                      <li><%= link_to "Status", "footer_path" %></li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Contact us </h3>
                    <ul>
                      <li><%= link_to "About us", "footer_path" %></li>
                      <li><%= link_to "Our Blog", "footer_path" %></li>
                      <li><%= link_to "Careers", "footer_path" %></li>
                    </ul>
                </div>

<div class="col-lg-3  col-md-3 col-sm-6 col-xs-6 ">
    <h3> Newsletter </h3>
      <ul>
          <li>
            <div class="input-append newsletter-box text-center">
                  <input type="text" class="full text-center" placeholder="Email ">
                  <button class="btn  bg-gray" type="button"><%= link_to "Sign Up", "newslettersignup_path"  %><i class="fa fa-long-arrow-right"></i>
                  </button>
            </div>
          </li>
      </ul>
<!-- <a class="btn btn-block btn-social btn-twitter">
    <span class="fa fa-twitter"></span> Sign in with Twitter
</a>
<a class="btn btn-block btn-social btn-dropbox">
    <span class="fa fa-dropbox"></span> Sign in with Dropbox -->
</a>
<a href= "https://nl-nl.facebook.com/login/" class="btn btn-block btn-social btn-facebook">
    <span class="fa fa-facebook"></span> Sign in with Facebook

 </a>
<a href= "https://github.com/login" class="btn btn-block btn-social btn-github">
    <span class="fa fa-github"></span> Sign in with Github

</a>
      </div>
            </div> -->
          <!--/.row-->
        </div>
        <!--/.container-->
    </div>


    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © Hourify 2016. All right reserved. </p>
            <div class="pull-right">
                <ul class="nav nav-pills payments">
                    <li><i class="fa fa-cc-visa"></i></li>
                    <li><i class="fa fa-cc-mastercard"></i></li>
                    <li><i class="fa fa-cc-amex"></i></li>
                    <li><i class="fa fa-cc-paypal"></i></li>
                </ul>
            </div>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>
</center>

app/views/shared/_navigation.html.erb
<center>
<nav class="navbar navbar-inverse navbar-fixed-top navi" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class = "search">
             <%= form_tag(items_path, :method => "get", id: "search-form") do %>
              <%= search_field_tag :search, params[:search], placeholder: "Search" %>
             <%= submit_tag "Search" %>
              <% end %>
          </div>
      <%= image_tag("", :class => "logo") %>
      <!-- <%= link_to "Tree Huggers", root_path , class: "navbar-brand" %> -->
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <div class = "pull-right">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path%></li>
          <li><%= link_to "Contact", contact_path%></li>
          <% if user_signed_in? %>
            <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>
</center>

app/views/shared/_newslettersignup.html.erb
<h2 class="newsletter">
Thanks for signing up for out newsletter!
</h2>

app/views/shared/newslettersignup.html.erb
<h2 class="newsletter">
Thanks for signing up for out newsletter!
</h2>